apiVersion: apps/v1
kind: Deployment
metadata:
  name: timbre
  namespace: timbre
  labels:
    app: timbre
    version: "${VERSION}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timbre
  template:
    metadata:
      labels:
        app: timbre
        version: "${VERSION}"
    spec:
      containers:
      - name: timbre
        image: ${DOCKER_REGISTRY}/timbre:${VERSION}-amd64
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/timbre
        - name: logs-volume
          mountPath: /var/log/timbre
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: TIMBRE_LOG_LEVEL
          value: "info"
        - name: TIMBRE_ENV
          valueFrom:
            configMapKeyRef:
              name: timbre-config
              key: environment
      volumes:
      - name: config-volume
        configMap:
          name: timbre-config
      - name: logs-volume
        emptyDir: {} 