name: Discord Notification

on:
  workflow_dispatch:
#   release:
#     types: [published]
#   pull_request:
#     types: [closed]
#     branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            # Release notification
            curl -X POST $DISCORD_WEBHOOK \
              -H "Content-Type: application/json" \
              -d '{
                "embeds": [{
                  "title": "🚀 New Release: Timbre ${{ github.event.release.tag_name }}",
                  "description": "A new version has been released!",
                  "url": "${{ github.event.release.html_url }}",
                  "color": 5814783,
                  "fields": [
                    {
                      "name": "Version",
                      "value": "${{ github.event.release.tag_name }}",
                      "inline": true
                    },
                    {
                      "name": "Author",
                      "value": "${{ github.actor }}",
                      "inline": true
                    }
                  ]
                }]
              }'
          elif [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            # PR merge notification
            curl -X POST $DISCORD_WEBHOOK \
              -H "Content-Type: application/json" \
              -d '{
                "embeds": [{
                  "title": "🔄 PR Merged: ${{ github.event.pull_request.title }}",
                  "description": "A pull request has been merged into main",
                  "url": "${{ github.event.pull_request.html_url }}",
                  "color": 7506394,
                  "fields": [
                    {
                      "name": "PR Number",
                      "value": "#${{ github.event.pull_request.number }}",
                      "inline": true
                    },
                    {
                      "name": "Author",
                      "value": "${{ github.event.pull_request.user.login }}",
                      "inline": true
                    }
                  ]
                }]
              }'
          fi 