name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      skip_release: ${{ steps.validate.outputs.skip_release }}
      bump_type: ${{ steps.validate.outputs.bump_type }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Validate PR template
        id: validate
        run: |
          BUMP_TYPE=none
          SKIP_RELEASE=false
          
          # For pull requests, check if it was merged
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # Only proceed if the PR was merged
            if [[ "${{ github.event.pull_request.merged }}" != "true" ]]; then
              echo "Pull request was closed without merging, skipping release"
              BUMP_TYPE=none
              SKIP_RELEASE=true
              echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT
              echo "skip_release=$SKIP_RELEASE" >> $GITHUB_OUTPUT
              exit 0
            fi
            
            PR_BODY="${{ github.event.pull_request.body }}"
                
            if ! echo "$PR_BODY" | grep -q "\[.\] MAJOR:" && \
              ! echo "$PR_BODY" | grep -q "\[.\] MINOR:" && \
              ! echo "$PR_BODY" | grep -q "\[.\] PATCH:" && \
              ! echo "$PR_BODY" | grep -q "\[.\] NONE:"; then
                echo "Error: PR template is missing version bump fields"
                echo "Expected fields:"
                echo "  [ ] MAJOR:"
                echo "  [ ] MINOR:"
                echo "  [ ] PATCH:"
                echo "  [ ] NONE:"
                echo "Assuming no bump intended"
                BUMP_TYPE=none
                SKIP_RELEASE=true
            else
                # Check if exactly one version bump option is selected
                SELECTED_COUNT=$(echo "$PR_BODY" | grep -c "\[\\S\]")
                echo "Found $SELECTED_COUNT selected options"
                
                if [ "$SELECTED_COUNT" -ne 1 ]; then
                  echo "Error: Exactly one version bump option must be selected"
                  echo "Selected options:"
                  echo "$PR_BODY" | grep "\[\\S\]" || true
                  exit 1
                fi
                
                if echo "$PR_BODY" | grep -q "\[\\S\] MAJOR:"; then
                    echo "Selected: MAJOR version bump"
                    BUMP_TYPE=major
                elif echo "$PR_BODY" | grep -q "\[\\S\] MINOR:"; then
                    echo "Selected: MINOR version bump"
                    BUMP_TYPE=minor
                elif echo "$PR_BODY" | grep -q "\[\\S\] PATCH:"; then
                    echo "Selected: PATCH version bump"
                    BUMP_TYPE=patch
                else
                    echo "Selected: NO version bump"
                    BUMP_TYPE=none
                    SKIP_RELEASE=true
                fi
            fi
          else
            # For workflow_dispatch, always proceed with build release
            echo "Manual workflow dispatch detected, proceeding with BUILD version bump"
            BUMP_TYPE=build
            SKIP_RELEASE=false
          fi
              
          echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT
          echo "skip_release=$SKIP_RELEASE" >> $GITHUB_OUTPUT

  get_version:
    needs: validate
    if: ${{ needs.validate.outputs.skip_release != 'true' }}
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.parse_version.outputs.current_version }}
      major: ${{ steps.parse_version.outputs.major }}
      minor: ${{ steps.parse_version.outputs.minor }}
      patch: ${{ steps.parse_version.outputs.patch }}
      build: ${{ steps.parse_version.outputs.build }}
      is_build_version: ${{ steps.parse_version.outputs.is_build_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Parse version
        id: parse_version
        run: |
          CURRENT_VERSION=$(cat pkg/version.txt)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          
          # Extract semantic version parts using regex
          if [[ "$CURRENT_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(?:\+([0-9]+))?$ ]]; then
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            BUILD="${BASH_REMATCH[4]:-}"
            
            echo "major=$MAJOR" >> $GITHUB_OUTPUT
            echo "minor=$MINOR" >> $GITHUB_OUTPUT
            echo "patch=$PATCH" >> $GITHUB_OUTPUT
            echo "build=$BUILD" >> $GITHUB_OUTPUT
            
            if [ -n "$BUILD" ]; then
              echo "is_build_version=true" >> $GITHUB_OUTPUT
            else
              echo "is_build_version=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "Error: Version format is invalid. Expected format: X.Y.Z or X.Y.Z+N"
            echo "Current version: $CURRENT_VERSION"
            exit 1
          fi

  version:
    needs: [validate, get_version]
    if: ${{ needs.validate.outputs.skip_release != 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TIMBRE_TOKEN }}
      
      - name: Setup Git
        run: |
          # Prevent ownership errors in container environments
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          
          # Ensure we can push changes
          git remote -v || true
          if ! git remote -v | grep -q origin; then
            git remote add origin "https://x-access-token:${{ secrets.TIMBRE_TOKEN }}@github.com/krakjn/timbre.git"
          fi
      
      - name: Bump version
        id: bump
        run: |
          BUMP_TYPE="${{ needs.validate.outputs.bump_type }}"
          MAJOR="${{ needs.get_version.outputs.major }}"
          MINOR="${{ needs.get_version.outputs.minor }}"
          PATCH="${{ needs.get_version.outputs.patch }}"
          
          if [ "$BUMP_TYPE" = "build" ]; then
            # For workflow_dispatch, add build number
            NEW_BUILD_NUMBER=$(git rev-list --count HEAD)
            NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}+${NEW_BUILD_NUMBER}"
            echo "Bumping build number: $NEW_VERSION"
          else
            # For pull requests, bump according to the selected type
            case "$BUMP_TYPE" in
              "major")
                NEW_VERSION="$((MAJOR + 1)).0.0"
                ;;
              "minor")
                NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
                ;;
              "patch")
                NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
                ;;
              *)
                NEW_VERSION="$MAJOR.$MINOR.$PATCH"  # no bump
                ;;
            esac
            echo "Bumping version: $NEW_VERSION"
          fi
          
          echo "$NEW_VERSION" > pkg/version.txt
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
      
      - name: Commit version change
        run: |
          git add pkg/version.txt
          
          NEW_VERSION="${{ steps.bump.outputs.new_version }}"
          git commit -m "chore: bump version to $NEW_VERSION"
          
          # Push to the appropriate branch
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For merged PRs, push to the target branch (main)
            git push origin HEAD:main
          else
            # For workflow_dispatch, push to the current branch
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          fi
      
      - name: Create Git tag
        run: |
          NEW_VERSION="${{ steps.bump.outputs.new_version }}"
          git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"
          git push origin "$NEW_VERSION"

  build:
    needs: [version, validate]
    if: ${{ needs.validate.outputs.skip_release != 'true' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krakjn/timbre
      credentials:
        username: krakjn
        password: ${{ secrets.TIMBRE_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Build package
        run: |
          make deb BUILD_TYPE=Release
      
      - name: Install and verify package
        run: |
          if ! dpkg -i build/*.deb; then
            echo "Failed to install package"
            exit 1
          fi
          
          if ! version_output=$(timbre --version); then
            echo "Failed to run timbre --version"
            exit 1
          fi
          echo "Version check output: $version_output"
          
          if ! help_output=$(timbre --help); then
            echo "Failed to run timbre --help"
            exit 1
          fi
          echo "Help command output: $help_output"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: timbre-deb
          path: build/*.deb
          retention-days: 7

  release:
    needs: [build, version, get_version, validate]
    if: ${{ needs.validate.outputs.skip_release != 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/krakjn/timbre
      credentials:
        username: krakjn
        password: ${{ secrets.TIMBRE_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TIMBRE_TOKEN }}
      
      - name: Setup Git
        run: |
          # Prevent ownership errors in container environments
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          
          # Ensure we can push changes
          git remote -v || true
          if ! git remote -v | grep -q origin; then
            git remote add origin "https://x-access-token:${{ secrets.TIMBRE_TOKEN }}@github.com/krakjn/timbre.git"
          fi
      
      - name: Generate changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          # Pull before generating changelog to avoid conflicts
          git pull
          
          if [ -n "$PREV_TAG" ]; then
            auto-changelog \
              --template keepachangelog \
              --output CHANGELOG.md \
              --commit-limit false \
              --unreleased true \
              --hide-credit true \
              --starting-commit $PREV_TAG
          else
            auto-changelog \
              --template keepachangelog \
              --output CHANGELOG.md \
              --commit-limit false \
              --unreleased true \
              --hide-credit true
          fi
          
          git add CHANGELOG.md
          git commit -m "docs: update changelog for ${{ needs.version.outputs.new_version }}"
          
          # Push to the appropriate branch
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For merged PRs, push to the target branch (main)
            git push origin HEAD:main
          else
            # For workflow_dispatch, push to the current branch
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          fi
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: timbre-deb
          path: build
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.deb
            CHANGELOG.md
          draft: ${{ needs.get_version.outputs.is_build_version }}
          prerelease: false
          tag_name: ${{ needs.version.outputs.new_version }}
          title: Release ${{ needs.version.outputs.new_version }}
          body: |
            See CHANGELOG.md for details.
            
            ## Installation
            
            ### Debian Package
            ```bash
            sudo dpkg -i timbre_${{ needs.version.outputs.new_version }}*.deb
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
