name: Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      skip_release: ${{ steps.validate.outputs.skip_release }}
      bump_type: ${{ steps.validate.outputs.bump_type }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Validate PR template
        id: validate
        shell: bash
        run: |
          BUMP_TYPE=none
          SKIP_RELEASE=false
          
          # For pull requests, check if it was merged
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # Only proceed if the PR was merged
            if [[ "${{ github.event.pull_request.merged }}" != "true" ]]; then
              echo "Pull request was closed without merging, skipping release"
              BUMP_TYPE=none
              SKIP_RELEASE=true
              echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT
              echo "skip_release=$SKIP_RELEASE" >> $GITHUB_OUTPUT
              exit 0
            fi
            
            PR_BODY="${{ github.event.pull_request.body }}"
                
            if ! echo "$PR_BODY" | grep -q "\[.\] MAJOR:" && \
              ! echo "$PR_BODY" | grep -q "\[.\] MINOR:" && \
              ! echo "$PR_BODY" | grep -q "\[.\] PATCH:" && \
              ! echo "$PR_BODY" | grep -q "\[.\] NONE:"; then
                echo "Error: PR template is missing version bump fields"
                echo "Expected fields:"
                echo "  [ ] MAJOR:"
                echo "  [ ] MINOR:"
                echo "  [ ] PATCH:"
                echo "  [ ] NONE:"
                echo "Assuming no bump intended"
                SKIP_RELEASE=true
            else
                # Check if exactly one version bump option is selected
                SELECTED_COUNT=$(echo "$PR_BODY" | grep -c "\[\\S\] \(MAJOR\|MINOR\|PATCH\|NONE\):")
                echo "Found $SELECTED_COUNT selected options"
                
                if [ "$SELECTED_COUNT" -ne 1 ]; then
                  echo "Error: Exactly one version bump option must be selected"
                  echo "Selected options:"
                  echo "$PR_BODY" | grep "\[\\S\]" || true
                  exit 1
                fi
                
                if echo "$PR_BODY" | grep -q "\[\\S\] MAJOR:"; then
                    echo "Selected: MAJOR version bump"
                    BUMP_TYPE=major
                elif echo "$PR_BODY" | grep -q "\[\\S\] MINOR:"; then
                    echo "Selected: MINOR version bump"
                    BUMP_TYPE=minor
                elif echo "$PR_BODY" | grep -q "\[\\S\] PATCH:"; then
                    echo "Selected: PATCH version bump"
                    BUMP_TYPE=patch
                else
                    echo "Selected: NO version bump"
                    SKIP_RELEASE=true
                fi
            fi
          else # not a PR
            echo "Manual workflow dispatch detected, proceeding with DEV version bump"
            BUMP_TYPE=dev
            SKIP_RELEASE=false
          fi
              
          echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT
          echo "skip_release=$SKIP_RELEASE" >> $GITHUB_OUTPUT

  version:
    needs: [validate]
    if: ${{ needs.validate.outputs.skip_release != 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/krakjn/timbre
      credentials:
        username: krakjn
        password: ${{ secrets.TIMBRE_TOKEN }}
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
      dev_version: ${{ steps.bump.outputs.dev_version }}
      changelog: ${{ steps.changelog.outputs.content }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Git
        run: |
          # Prevent ownership errors in container environments
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          
          # Ensure we can push changes
          git remote -v || true
          if ! git remote -v | grep -q origin; then
            git remote add origin "https://x-access-token:${{ secrets.TIMBRE_TOKEN }}@github.com/krakjn/timbre.git"
          fi
      
      - name: Parse version
        id: parse_version
        shell: bash # sh doesn't support BASH_REMATCH
        run: |
          # cmake bakes in the version into the binary, so we need to parse it from the file
          CURRENT_VERSION=$(cat pkg/version.txt | tr -d '[:space:]')
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          
          # Extract semantic version parts using regex
          if [[ "$CURRENT_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then

            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            
            echo "major=$MAJOR" >> $GITHUB_OUTPUT
            echo "minor=$MINOR" >> $GITHUB_OUTPUT
            echo "patch=$PATCH" >> $GITHUB_OUTPUT
            
          else
            echo "Error: Version format is invalid. Expected format: X.Y.Z"
            echo "Current version: $CURRENT_VERSION"
            exit 1
          fi
      
      - name: Bump version
        id: bump
        shell: bash
        run: |
          BUMP_TYPE="${{ needs.validate.outputs.bump_type }}"
          MAJOR="${{ steps.parse_version.outputs.major }}"
          MINOR="${{ steps.parse_version.outputs.minor }}"
          PATCH="${{ steps.parse_version.outputs.patch }}"

          # CMake will query for main branch, if so release version
          # otherwise it will assign IS_DEV and be a dev version
          # For pull requests, bump according to the selected type
          case "$BUMP_TYPE" in
            "major")
              NEW_VERSION="$((MAJOR + 1)).0.0"
              ;;
            "minor")
              NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
              ;;
            "patch")
              NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
              ;;
            "dev")
              echo "skipping version bump"
              NEW_VERSION="$MAJOR.$MINOR.$PATCH"
              ;;
          esac

          echo "BUMP_TYPE=$BUMP_TYPE, NEW_VERSION=$NEW_VERSION"

          # Write the new version to the version file
          # always write a clean semver to pkg/version.txt
          echo "$NEW_VERSION" > pkg/version.txt
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

          # for dev releases
          echo "dev_version=$NEW_VERSION+$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT

      # Dev releases don't get a tag
      - name: Create Git tag
        if: ${{ needs.validate.outputs.bump_type != 'dev' }}
        shell: bash
        run: |
          TAG_NAME="${{ steps.bump.outputs.new_version }}"
          git tag -a "$TAG_NAME" -m "Release: $TAG_NAME"
          git push origin "$TAG_NAME"
      
      # now with a fresh tag, generate a changelog
      - name: Commit version bump with changelog
        id: changelog
        shell: bash
        if: ${{ needs.validate.outputs.bump_type != 'dev' }}
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD~2 2>/dev/null || echo "")
          auto-changelog --config cfg/auto-changelog --starting-version $PREV_TAG --output RELEASE_NOTES.md
          auto-changelog --config cfg/auto-changelog --output CHANGELOG.md

          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat RELEASE_NOTES.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          git add CHANGELOG.md pkg/version.txt
          git commit -m "chore: release ${{ steps.bump.outputs.new_version }}"
          
          # Push to the appropriate branch
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For merged PRs, push to the target branch (main)
            git push origin HEAD:main
          else
            # For workflow_dispatch, push to the current branch
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          fi

      # Build freshly bumped version
      - name: Build packages
        run: |
          zig build all --release=fast
          zig build package --release=fast
      
      - name: Install and verify package
        shell: bash
        run: |
          # Verify AMD64 package
          if ! dpkg -i zig-out/pkg/*amd64.deb; then
            echo "Failed to install AMD64 package"
            exit 1
          fi
          
          # Note: ARM64 package can't be verified in AMD64 container
          # but we can check if it exists
          if [ ! -f zig-out/pkg/*arm64.deb ]; then
            echo "ARM64 package not found"
            exit 1
          fi
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: timbre-artifacts
          path: |
            zig-out/pkg/*.deb
            zig-out/aarch64-linux-musl/timbre
            zig-out/x86_64-linux-musl/timbre
            zig-out/aarch64-macos/timbre
            zig-out/x86_64-macos/timbre
            zig-out/aarch64-windows/timbre.exe
            zig-out/x86_64-windows/timbre.exe
          retention-days: 7

  release:
    needs: [validate, version]
    if: ${{ needs.validate.outputs.skip_release != 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      changelog: ${{ needs.version.outputs.changelog }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: timbre-artifacts

      - name: Prepare Release Assets
        id: prepare
        run: |
          VERSION="${{ needs.version.outputs.new_version }}"
          if ${{ needs.validate.outputs.bump_type == 'dev' }}; then
            VERSION="${{ needs.version.outputs.dev_version }}"
          fi

          mkdir release
          # give the files better names
          mv aarch64-linux-musl/timbre "release/timbre-${VERSION}-linux-arm64"
          mv x86_64-linux-musl/timbre "release/timbre-${VERSION}-linux-x86_64"
          mv aarch64-macos/timbre "release/timbre-${VERSION}-macos-arm64"
          mv x86_64-macos/timbre "release/timbre-${VERSION}-macos-x86_64"
          mv aarch64-windows/timbre.exe "release/timbre-${VERSION}-windows-arm64.exe"
          mv x86_64-windows/timbre.exe "release/timbre-${VERSION}-windows-x86_64.exe"
          mv pkg/*.deb "release/"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            release/*
          draft: ${{ needs.validate.outputs.skip_release == 'true' }}
          prerelease: false
          tag_name: ${{ needs.version.outputs.new_version }}
          body: |
            ${{ needs.version.outputs.changelog }}
